name: alpine-image-build

on:
  schedule:
    - cron: "0 0 * * 1"   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update -qq
          sudo apt install -qq -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          for i in $(cat versions); do cd ${i}; docker buildx build --push --platform 'linux/amd64,linux/arm64' --builder builder -t jnix85/unbound:${i} .; cd .. ; done
